### ISSUE TITLE
Procedure or function 'Instance_Create' expects parameter '@Created', which was not supplied.

### ISSUE THREAD

**Issue by taintedzodiac** [webdestroya/lita-memegen#9]
In the past couple of days, I've been seeing this error in the logs every time that the bot attempts to create a meme. No recent changes to our bot, running on the latest lita-memegen version.

`ERROR: MemeGenerator: Unable to generate a meme image: {"success"=>false, "errorMessage"=>"Procedure or function 'Instance_Create' expects parameter '@Created', which was not supplied."}`

**Comment by ProbablyRusty** [comment]
Seeing the same:

```
[2015-06-04 17:46:54 UTC] ERROR: MemeGenerator: Unable to generate a meme image: {"success"=>false, "errorMessage"=>"Procedure or function 'Instance_Create' expects parameter '@Created', which was not supplied."}
```

**Comment by ProbablyRusty** [comment]
This seems to be a new issue with the API. Here is the message I sent to memgenerator.net support:

```
For the past few weeks I have been getting this failure when calling Instance_Create:

{"success":false,"errorMessage":"Procedure or function \u0027Instance_Create\u0027 expects parameter \u0027@Created\u0027, which was not supplied.”}

A “created” parameter does not seem to be documented in:

http://version1.api.memegenerator.net/#Instance_Create

I have tried sending a dummy value for “created”, but get the same error:

http://version1.api.memegenerator.net/Instance_Create?created=true&username=REDACTED&password=REDACTED&languageCode=en&generatorID=45&imageID=20&text0=push%20a%20hipster%20down%20the%20stairs&text1=now%20look%20who's%20tumbling


Can you provide any insight?

This behavior seems to have changed about 3 weeks ago.
```

**Comment by vanchagreen** [comment]
I've got a script that uses the memegenerator API, and I'm getting the same error. Have you heard anything back from them?

**Comment by ProbablyRusty** [comment]
No, I have not received any response.

**Comment by thoersch** [comment]
I've emailed them again as well as it's definitely on their side with the stored procedure.  If I get a response, I will update here too.

**Comment by webdestroya** [comment]
@thoersch So is this error completely on memgenerator's side?

**Comment by thoersch** [comment]
Based on the error message, definitely

**Comment by ProbablyRusty** [comment]
I wonder if it might be worthwhile to port `lita-memegen` to this instead:

http://apimeme.com

Or, if I get time, maybe I will consider writing a lita plugin from scratch which is based on this API, or maybe submitting a PR to add support for this API to `lita-memegen`.

**Comment by khanh-nguyen** [comment]
I'm running into the same problem. Have you got any response from meme-generator team, @thoersch ?

**Comment by ProbablyRusty** [comment]
No response. I still hope to write a plugin based on apimeme.com, but have not had the time to do it just yet.

**Comment by msabramo** [comment]
I'm also getting this error and I'm using the hubot plugin for memegenerator.net.

So definitely their problem I think, even thought that was already pretty obvious.

**Comment by redwards510** [comment]
I am getting the error using meme_generator.coffee hubot script. I tried adding &Created=20151101 to the URL to pass the missing parameter but I think there is a disconnect between the API and the backend stored procedure. Looks like they abandoned their support too. :(

**Comment by msabramo** [comment]
Yeah adding a query string parameter doesn't work because I'm 98% sure that error is coming from a MS SQL stored procedure.

**Comment by taintedzodiac** [comment]
Seeing as the bot started working again a few weeks back, seems safe to close this.
